---
title: "Topic ideas"
author: "Power Ninja Data Turtles"
date: "10.11.2019"
output: github_document
---

## Topic Ideas

### Idea #1

Determining the most successful international soccer teams in FIFA World Cup Matches throughout time (1930-2014) based on the number of goals scored.

### Idea #2

Analyzing changes in the characteristics of college football offenses over time (formations, personnel, play-calling) and how they have contributed to increases in offensive output.

### Idea #3 

Analyzing TED Talks by topic over time to see which characteristics contribute to popularity and how they relate to the prevailing culture of the period.

### Idea #4

Analyzing the top 100 Spotify songs from 2018 to determine which characteristics contribute to popularity and what musical features are associated with certain genres.

## Datasets

### Dataset #1

WorldCupMatches.csv (https://www.kaggle.com/abecklas/fifa-world-cup#WorldCupMatches.csv)

This dataset is related to Idea #1, and it includes information concerning all matches from every FIFA World Cup tournament during the period of 1930-2014.

### Dataset #2

ted_main.csv (https://www.kaggle.com/rounakbanik/ted-talks)

This dataset is related to Idea #3 regarding the popularity and relatedness of TED Talks throughout the 2000's.

### Dataset #3

top2018.csv (https://www.kaggle.com/nadintamer/top-spotify-tracks-of-2018)

This dataset is related to Idea #4 regarding the top 100 Spotify songs from 2018.