---
title: "PROJECT TITLE"
author: "Power Ninja Data Turtles"
date: "October 23, 2019"
output: github_document
---

### Section 1. Introduction

For our research project, we will be analyzing the fight songs of various college football teams in order to discover the patterns and similar characteristics between them. To be more specific, we will be looking at the fight songs of all 67 teams located across the Power 5 sports conferences (Big 10, Big 12, ACC, Pac-12 and SEC). Our dataset, which is fittingly titled “fight-songs”, is a part of the fivethirtyeight package in R. Each observation in the set represents a distinct Power 5 college football team. For each team (observation), the dataset features 23 observations (of which we are using 19, plus one of our own) which contain a wide range of information, mostly about the school’s fight song. 
  
The variables are as follows: school (school name), conference (the school’s conference), song_name (the song’s title), writers (the song’s author(s)), year (the year the song was written), student_writer (whether or not the author was a student), official_song (if the school counts the song as their official fight song), bpm (beats per minute), sec_duration (duration of the song in seconds), fight (if the song mentions the word “fight”), number_fights (number of times “fight” is mentioned), victory_win_won (if the song mentions any of the words “victory”, “win” or “won”), rah (if the song mentions the word “rah”), nonsense (if the song includes any non-word sounds), colors (if the song mentions the school’s colors), men (if the song mentions a group of men/boys), opponents (if the song mentions any opponents), spelling (if, during the song, anything is spelled out), trope_count (total number of tropes --> fight, rah, nonsense, colors, men, opponents and spelling), and finally, rank (the historic AP rank of the school’s football team). 
  
The data was collected by looking at the lyrics of each song, history about each song, and information about each school’s conference. We added the rank variable to the dataset in Excel, and we found the data from the Associated Press’ historic rankings of every single college football team in the country, which was released last year. 
  
Through our analysis, we hope to see if any characteristics between songs (duration, number of tropes, etc) are common within the conferences and across the entire set of observations. We added the rank variable because we were interested in seeing if higher-ranked (more successful) teams had any commonalities between their respective fight songs, as well.

### Section 2. Exploratory data analysis

### Section 3. Research questions

### Section 4. Data

